import Link from "next/link";
import { ArrowRight, BookOpen, BrainCircuit, Check, ChevronRight, ClipboardCheck, Code2, Sparkles, Target, TrendingUp } from "lucide-react";

import { AppShell } from "@/components/app-shell/app-shell";

// Temporary presentation-only data. This will be replaced when dashboard data is connected.
const skillGaps = [
  { label: "System Design", progress: 38 },
  { label: "Data Structures", progress: 52 },
  { label: "Interview Communication", progress: 46 },
];

const planItems = [
  { title: "Complete SQL joins practice", detail: "45 min · Skill builder", done: true },
  { title: "Review your interview answers", detail: "20 min · AI feedback", done: false },
  { title: "Explore target company questions", detail: "15 min · Question bank", done: false },
];

export default function Home() {
  return <AppShell title="Dashboard"><div className="mx-auto flex w-full max-w-7xl flex-col gap-5">
    <section className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><div className="mb-2 flex items-center gap-2 text-xs font-medium text-primary"><span className="flex size-5 items-center justify-center rounded-md bg-primary/10"><Sparkles className="size-3" aria-hidden="true" /></span>CAREER INTELLIGENCE PREVIEW</div><h2 className="text-2xl font-semibold tracking-tight sm:text-3xl">Good morning, Student.</h2><p className="mt-1.5 max-w-2xl text-sm leading-6 text-muted-foreground">Here&apos;s a focused view of what moves your placement readiness forward today.</p></div><span className="w-fit rounded-full border border-border bg-card px-3 py-1.5 text-xs text-muted-foreground">Demo preview · Backend data coming soon</span></section>

    <section className="grid gap-4 xl:grid-cols-[1.35fr_0.85fr]"><article className="rounded-xl border border-border bg-card p-5 shadow-sm sm:p-6"><div className="flex items-start justify-between gap-4"><div><div className="flex items-center gap-2 text-sm font-medium"><span className="flex size-7 items-center justify-center rounded-lg bg-primary/10 text-primary"><Target className="size-4" aria-hidden="true" /></span>Career readiness</div><p className="mt-3 text-3xl font-semibold tracking-tight">68%</p><p className="mt-1 text-sm text-muted-foreground">On track for a Software Engineer role</p></div><div className="flex items-center gap-1 rounded-lg bg-primary/10 px-2.5 py-1.5 text-xs font-medium text-primary"><TrendingUp className="size-3.5" aria-hidden="true" />+8 this month</div></div><div className="mt-6 h-2 overflow-hidden rounded-full bg-muted" role="progressbar" aria-label="Career readiness" aria-valuemin={0} aria-valuemax={100} aria-valuenow={68}><div className="h-full w-[68%] rounded-full bg-primary" /></div><div className="mt-4 grid grid-cols-3 gap-3 border-t border-border pt-4 text-sm"><div><p className="font-semibold">12</p><p className="mt-0.5 text-xs text-muted-foreground">Skills mapped</p></div><div><p className="font-semibold">2</p><p className="mt-0.5 text-xs text-muted-foreground">Improving</p></div><div><p className="font-semibold">3</p><p className="mt-0.5 text-xs text-muted-foreground">Focus areas</p></div></div></article>
      <article className="rounded-xl border border-primary/20 bg-primary/[0.035] p-5 sm:p-6"><div className="flex items-center gap-2 text-sm font-medium text-primary"><Sparkles className="size-4" aria-hidden="true" />NEXT BEST ACTION</div><h3 className="mt-3 text-lg font-semibold tracking-tight">System Design is your highest-impact gap.</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">Continue System Design Fundamentals for 35 minutes, then use an AI practice prompt to retain it.</p><Link href="/learn-practice" className="mt-5 inline-flex items-center gap-1.5 text-sm font-medium text-primary transition-colors hover:text-primary/80">Continue learning <ArrowRight className="size-3.5" /></Link></article></section>

    <section className="grid gap-4 lg:grid-cols-2"><article className="rounded-xl border border-border bg-card p-5 shadow-sm"><div className="flex items-start justify-between gap-4"><div><div className="flex items-center gap-2 text-sm font-medium"><Code2 className="size-4 text-primary" aria-hidden="true" />Skill-gap focus</div><p className="mt-1 text-sm text-muted-foreground">The capabilities that will make the biggest difference next.</p></div><Link href="/career-skill-gap" className="inline-flex shrink-0 items-center gap-1 text-xs font-medium text-primary transition-colors hover:text-primary/80">View map <ChevronRight className="size-3.5" aria-hidden="true" /></Link></div><div className="mt-5 space-y-4">{skillGaps.map((skill) => <div key={skill.label}><div className="mb-1.5 flex items-center justify-between text-sm"><span>{skill.label}</span><span className="text-xs text-muted-foreground">{skill.progress}% confidence</span></div><div className="h-1.5 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-primary/80" style={{ width: `${skill.progress}%` }} /></div></div>)}</div></article>
      <article className="rounded-xl border border-border bg-card p-5 shadow-sm"><div className="flex items-start justify-between gap-4"><div><div className="flex items-center gap-2 text-sm font-medium"><ClipboardCheck className="size-4 text-primary" aria-hidden="true" />Your plan</div><p className="mt-1 text-sm text-muted-foreground">AI-recommended steps for this week.</p></div><span className="rounded-md bg-primary/10 px-2 py-1 text-[11px] font-medium text-primary">AI recommended</span></div><ul className="mt-4 divide-y divide-border">{planItems.map((item) => <li key={item.title} className="flex items-center gap-3 py-3 first:pt-0 last:pb-0"><span className={item.done ? "flex size-5 shrink-0 items-center justify-center rounded-full bg-primary text-primary-foreground" : "flex size-5 shrink-0 items-center justify-center rounded-full border border-border text-transparent"}><Check className="size-3" aria-hidden="true" /></span><span className="min-w-0 flex-1"><span className={item.done ? "block text-sm text-muted-foreground line-through" : "block text-sm font-medium"}>{item.title}</span><span className="mt-0.5 block text-xs text-muted-foreground">{item.detail}</span></span>{!item.done && <ChevronRight className="size-4 text-muted-foreground" aria-hidden="true" />}</li>)}</ul></article></section>

    <section aria-labelledby="quick-actions-title" className="rounded-xl border border-border bg-card p-5 shadow-sm"><div><h2 id="quick-actions-title" className="text-sm font-medium">Continue your momentum</h2><p className="mt-1 text-sm text-muted-foreground">Choose a focused action for today.</p></div><div className="mt-4 grid gap-3 sm:grid-cols-3">{[{ icon: BrainCircuit, title: "Practice with AI", detail: "Run a mock interview", href: "/ai-communication" }, { icon: BookOpen, title: "Build a skill", detail: "Continue System Design", href: "/learn-practice" }, { icon: Target, title: "Check role fit", detail: "Review your target path", href: "/career-skill-gap" }].map((action) => { const Icon = action.icon; return <Link key={action.title} href={action.href} className="group flex items-center gap-3 rounded-lg border border-border p-3 text-left transition-colors hover:border-primary/30 hover:bg-primary/[0.025] focus-visible:outline-none focus-visible:ring-3 focus-visible:ring-ring/50"><span className="flex size-9 shrink-0 items-center justify-center rounded-lg bg-muted text-primary transition-colors group-hover:bg-primary/10"><Icon className="size-4" aria-hidden="true" /></span><span className="min-w-0"><span className="block text-sm font-medium">{action.title}</span><span className="mt-0.5 block text-xs text-muted-foreground">{action.detail}</span></span><ChevronRight className="ml-auto size-4 text-muted-foreground" aria-hidden="true" /></Link>; })}</div></section>
  </div></AppShell>;
}
