"use client";
import { useEffect, useSyncExternalStore } from "react";
export type ReadinessSkill={name:string;current:number;target:number};
export type ReadinessState={learning:number;coding:number;communication:number;interview:number;skills:ReadinessSkill[];history:{date:string;score:number;reason:string;impact:number}[]};
const KEY="skillora-readiness"; const baseline:ReadinessState={learning:74,coding:61,communication:68,interview:64,skills:[{name:"JavaScript & TypeScript",current:78,target:75},{name:"Problem Solving",current:74,target:80},{name:"Data Structures",current:52,target:78},{name:"System Design",current:38,target:70},{name:"Interview Communication",current:46,target:72}],history:[{date:"Aug 15",score:62,reason:"Baseline assessment",impact:0},{date:"Aug 16",score:64,reason:"Learning progress",impact:2},{date:"Aug 17",score:65,reason:"Coding practice",impact:1},{date:"Aug 18",score:68,reason:"Skill assessment",impact:3}]};
const listeners=new Set<()=>void>(); function load(){if(typeof window==="undefined")return baseline;try{return JSON.parse(localStorage.getItem(KEY)||"null")||baseline}catch{return baseline}} let state=baseline;
export function score(s=state){const skills=s.skills.reduce((a,x)=>a+Math.min(100,x.current)/s.skills.length,0);return Math.round(skills*.35+s.coding*.2+s.learning*.15+s.communication*.15+s.interview*.15)}
function emit(){if(typeof window!=="undefined")localStorage.setItem(KEY,JSON.stringify(state));listeners.forEach(l=>l())}
export function hydrateReadiness(){state=load();emit()}
export function recordReadiness(kind:"learning"|"coding"|"communication"|"interview", detail:string, skill?:string){const before=score();const delta=kind==="learning"?5:kind==="coding"?4:kind==="communication"?4:5;state={...state,[kind]:Math.min(100,state[kind]+delta),skills:skill?state.skills.map(x=>x.name.toLowerCase().includes(skill.toLowerCase())?{...x,current:Math.min(100,x.current+delta)}:x):state.skills};const after=score();state={...state,history:[...state.history,{date:new Intl.DateTimeFormat("en",{month:"short",day:"numeric"}).format(new Date()),score:after,reason:detail,impact:after-before}].slice(-7)};emit()}
export function useReadiness(){const snapshot=useSyncExternalStore(cb=>{listeners.add(cb);return()=>listeners.delete(cb)},()=>state,()=>baseline);useEffect(()=>{state=load();listeners.forEach(l=>l())},[]);return snapshot}
