"use client";

import { useEffect, useMemo, useState } from "react";
import { Check, ChevronRight, Code2, Lightbulb, LoaderCircle, RotateCcw, Send, Terminal, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";
import { recordReadiness } from "@/lib/readiness";
import { practiceLanguages, practiceProblems, runCodeDemo, type CodeExecutionResult, type PracticeLanguageId, type PracticeProblem } from "@/lib/code-practice";

type Filter = "All" | "Data Structures" | "Algorithms" | "SQL" | "Recommended";

export function CodePracticeLab({ onClose }: { onClose: () => void }) {
  const [problemId, setProblemId] = useState("two-sum");
  const [language, setLanguage] = useState<PracticeLanguageId>("python");
  const [code, setCode] = useState(practiceProblems[0].starterCode.python);
  const [filter, setFilter] = useState<Filter>("All");
  const [difficulty, setDifficulty] = useState<"All" | "Easy" | "Medium">("All");
  const [result, setResult] = useState<CodeExecutionResult | null>(null);
  const [state, setState] = useState<"idle" | "running" | "error" | "submitted">("idle");
  const [error, setError] = useState("");
  const selectedProblem = practiceProblems.find((problem) => problem.id === problemId) ?? practiceProblems[0];
  const visibleProblems = useMemo(() => practiceProblems.filter((problem) => (filter === "All" || (filter === "Recommended" ? problem.recommended : problem.skill === filter)) && (difficulty === "All" || problem.difficulty === difficulty)), [filter, difficulty]);

  useEffect(() => { const listener = (event: KeyboardEvent) => { if (event.key === "Escape") onClose(); }; window.addEventListener("keydown", listener); return () => window.removeEventListener("keydown", listener); }, [onClose]);
  function selectProblem(problem: PracticeProblem) { setProblemId(problem.id); setCode(problem.starterCode[language]); setResult(null); setState("idle"); setError(""); }
  function selectLanguage(next: PracticeLanguageId) { setLanguage(next); setCode(selectedProblem.starterCode[next]); setResult(null); setState("idle"); }
  async function run() { setState("running"); setError(""); try { setResult(await runCodeDemo({ language, code, problemId })); setState("idle"); } catch (caught) { setError(caught instanceof Error ? caught.message : "Code execution is temporarily unavailable."); setState("error"); } }
  async function submit() { setState("running"); setError(""); try { const output=await runCodeDemo({ language, code, problemId }); setResult(output); setState("submitted"); if(output.status==="passed") recordReadiness("coding", `${selectedProblem.title} practice completed`, selectedProblem.skill); } catch (caught) { setError(caught instanceof Error ? caught.message : "Code execution is temporarily unavailable."); setState("error"); } }
  const lineCount = Math.max(8, code.split("\n").length);
  return <div className="fixed inset-0 z-50 overflow-y-auto bg-muted/95 backdrop-blur-sm" role="dialog" aria-modal="true" aria-label="Code Practice Lab">
    <div className="mx-auto min-h-full max-w-[1600px] p-3 sm:p-5 lg:p-6"><header className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-border bg-card px-4 py-3 shadow-sm"><div className="flex items-center gap-3"><span className="flex size-9 items-center justify-center rounded-lg bg-primary text-primary-foreground"><Code2 className="size-4" /></span><div><h1 className="text-base font-semibold">Code Practice Lab</h1><p className="text-xs text-muted-foreground">Focused practice for your Software Engineer path</p></div></div><Button variant="outline" size="sm" onClick={onClose}>Back to Learn &amp; Practice <X data-icon="inline-end" /></Button></header>
      <section className="mt-4 grid gap-3 rounded-xl border border-primary/20 bg-primary/[0.035] p-4 sm:grid-cols-5"><div className="sm:col-span-2"><p className="text-xs font-medium text-primary">YOUR CODING PROGRESS</p><h2 className="mt-1 text-base font-semibold">Recommended next: Data Structures</h2><p className="mt-1 text-xs leading-5 text-muted-foreground">Recommended because Data Structures is one of your highest-impact skill gaps.</p></div>{[["6", "problems available"], ["2", "completed"], ["3", "skills practiced"]].map(([value, label]) => <div key={label}><p className="text-lg font-semibold">{value}</p><p className="text-xs text-muted-foreground">{label}</p></div>)}<div><p className="text-lg font-semibold">68%</p><p className="text-xs text-muted-foreground">readiness</p></div></section>
      <div className="mt-4 grid gap-4 xl:grid-cols-[330px_minmax(0,1fr)]"><aside className="rounded-xl border border-border bg-card p-4 shadow-sm"><h2 className="font-semibold">Practice problems</h2><div className="mt-3 flex flex-wrap gap-1.5">{(["All", "Data Structures", "Algorithms", "SQL", "Recommended"] as Filter[]).map((item) => <button key={item} onClick={() => setFilter(item)} className={cn("rounded-md px-2 py-1 text-xs font-medium focus-visible:outline-none focus-visible:ring-3 focus-visible:ring-ring/50", filter === item ? "bg-primary text-primary-foreground" : "bg-muted text-muted-foreground hover:text-foreground")}>{item}</button>)}</div><div className="mt-2 flex gap-1.5">{(["All", "Easy", "Medium"] as const).map((item) => <button key={item} onClick={() => setDifficulty(item)} className={cn("rounded-md border px-2 py-1 text-xs focus-visible:outline-none focus-visible:ring-3 focus-visible:ring-ring/50", difficulty === item ? "border-primary/35 text-primary" : "border-border text-muted-foreground")}>{item}</button>)}</div><div className="mt-4 space-y-2">{visibleProblems.map((problem) => <button key={problem.id} onClick={() => selectProblem(problem)} className={cn("w-full rounded-lg border p-3 text-left transition-colors focus-visible:outline-none focus-visible:ring-3 focus-visible:ring-ring/50", selectedProblem.id === problem.id ? "border-primary/35 bg-primary/[0.04]" : "border-border hover:border-primary/25")}><div className="flex justify-between gap-2"><span className="text-sm font-medium">{problem.title}</span>{problem.recommended ? <span className="text-[10px] font-medium text-primary">RECOMMENDED</span> : null}</div><p className="mt-1 text-xs text-muted-foreground">{problem.skill} · {problem.difficulty} · {problem.estimatedTime}</p></button>)}</div></aside>
        <main className="min-w-0 space-y-4"><div className="grid gap-4 lg:grid-cols-[0.38fr_0.62fr]"><article className="rounded-xl border border-border bg-card p-5 shadow-sm"><div className="flex flex-wrap items-center gap-2"><span className="rounded-md bg-primary/10 px-2 py-1 text-[11px] font-medium text-primary">{selectedProblem.skill}</span><span className="text-xs text-muted-foreground">{selectedProblem.difficulty} · {selectedProblem.estimatedTime}</span></div><h2 className="mt-4 text-xl font-semibold tracking-tight">{selectedProblem.title}</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">{selectedProblem.description}</p><h3 className="mt-5 text-sm font-semibold">Example</h3>{selectedProblem.examples.map((example) => <div key={example.input} className="mt-2 rounded-lg bg-muted p-3 font-mono text-xs leading-5"><p><span className="text-muted-foreground">Input:</span> {example.input}</p><p><span className="text-muted-foreground">Output:</span> {example.output}</p></div>)}<h3 className="mt-5 text-sm font-semibold">Constraints</h3><ul className="mt-2 space-y-1.5 text-xs leading-5 text-muted-foreground">{selectedProblem.constraints.map((constraint) => <li key={constraint}>• {constraint}</li>)}</ul></article>
            <article className="min-w-0 overflow-hidden rounded-xl border border-border bg-card shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-border px-4 py-3"><label className="text-sm font-semibold" htmlFor="language">{selectedProblem.responseMode === "structured" ? "Structured response" : "Code editor"}</label><select id="language" value={language} onChange={(event) => selectLanguage(event.target.value as PracticeLanguageId)} className="rounded-md border border-input bg-card px-2 py-1 text-xs outline-none focus-visible:ring-3 focus-visible:ring-ring/50">{practiceLanguages.map((item) => <option key={item.id} value={item.id}>{item.displayName}</option>)}</select></div><div className="grid min-h-75 grid-cols-[2.5rem_minmax(0,1fr)] bg-slate-950 text-slate-100"><pre aria-hidden="true" className="select-none border-r border-white/10 px-2 py-4 text-right font-mono text-xs leading-6 text-slate-500">{Array.from({ length: lineCount }, (_, index) => index + 1).join("\n")}</pre><textarea aria-label={selectedProblem.responseMode === "structured" ? "Structured response" : "Solution code"} value={code} onChange={(event) => setCode(event.target.value)} spellCheck={false} className="min-h-75 w-full resize-y bg-transparent px-4 py-4 font-mono text-xs leading-6 text-slate-100 outline-none" /></div><div className="flex flex-wrap justify-between gap-2 border-t border-border px-4 py-3"><Button variant="ghost" size="sm" onClick={() => { setCode(selectedProblem.starterCode[language]); setResult(null); setState("idle"); }}><RotateCcw data-icon="inline-start" />Reset</Button><div className="flex gap-2"><Button variant="outline" size="sm" disabled={state === "running"} onClick={run}>{state === "running" ? <LoaderCircle className="animate-spin" data-icon="inline-start" /> : <Terminal data-icon="inline-start" />}{state === "running" ? "Running tests..." : "Run code"}</Button><Button size="sm" disabled={state === "running"} onClick={submit}><Send data-icon="inline-start" />Submit solution</Button></div></div></article></div>
          <div className="grid gap-4 lg:grid-cols-2"><article className="rounded-xl border border-border bg-card p-5 shadow-sm"><div className="flex items-center gap-2"><Terminal className="size-4 text-primary" /><h2 className="font-semibold">Output / Test results</h2></div>{state === "running" ? <p className="mt-5 flex items-center gap-2 text-sm text-muted-foreground"><LoaderCircle className="size-4 animate-spin text-primary" />Running tests...</p> : error ? <div className="mt-4 rounded-lg border border-destructive/25 bg-destructive/5 p-3 text-sm"><p className="font-medium text-destructive">Code execution is temporarily unavailable.</p><p className="mt-1 text-xs text-muted-foreground">{error}</p><Button size="sm" variant="outline" className="mt-3" onClick={run}>Try demo runner</Button></div> : result ? <><div className="mt-4 flex items-center justify-between rounded-lg bg-primary/[0.04] p-3"><span className="flex items-center gap-2 text-sm font-medium text-primary"><Check className="size-4" />All tests passed</span><span className="text-xs text-muted-foreground">{result.testsPassed} / {result.testsTotal}</span></div><div className="mt-3 space-y-2">{result.tests.map((test) => <div key={test.name} className="flex items-center justify-between gap-2 text-xs"><span className="flex items-center gap-2"><Check className="size-3.5 text-primary" />{test.name}</span><span className="text-muted-foreground">{test.detail}</span></div>)}</div><p className="mt-4 text-xs text-muted-foreground">{result.executionTime} ms · Demo runner · Secure execution API coming soon</p></> : <p className="mt-5 text-sm text-muted-foreground">Run your solution to see test results.</p>}</article>
            <article className="rounded-xl border border-primary/20 bg-primary/[0.025] p-5 shadow-sm"><div className="flex items-center gap-2"><Lightbulb className="size-4 text-primary" /><h2 className="font-semibold">AI feedback</h2></div>{result ? <><p className="mt-3 text-sm leading-6 text-muted-foreground">{result.feedback.summary}</p><div className="mt-4 grid gap-3 sm:grid-cols-2"><div><h3 className="text-xs font-semibold text-primary">WHAT&apos;S WORKING</h3><ul className="mt-2 space-y-1 text-xs leading-5 text-muted-foreground">{result.feedback.working.map((item) => <li key={item}>• {item}</li>)}</ul></div><div><h3 className="text-xs font-semibold text-primary">IMPROVE NEXT</h3><ul className="mt-2 space-y-1 text-xs leading-5 text-muted-foreground">{result.feedback.improve.map((item) => <li key={item}>• {item}</li>)}</ul></div></div><div className="mt-4 flex flex-wrap items-center justify-between gap-2 border-t border-primary/15 pt-3"><p className="text-xs"><span className="font-medium">Next recommended:</span> Valid Parentheses</p><Button size="sm" variant="outline" onClick={() => selectProblem(practiceProblems.find((item) => item.id === result.feedback.nextProblemId) ?? practiceProblems[1])}>Practice next <ChevronRight data-icon="inline-end" /></Button></div>{state === "submitted" ? <div className="mt-4 rounded-lg border border-primary/20 bg-card p-3 text-sm"><p className="font-semibold text-primary">Solution submitted · +4 practice points</p><p className="mt-1 text-xs text-muted-foreground">Skill confidence signal updated. You&apos;re ready for a slightly harder challenge.</p></div> : null}<p className="mt-3 text-[11px] text-muted-foreground">Frontend demo feedback — live AI feedback will be connected through the backend.</p></> : <p className="mt-5 text-sm text-muted-foreground">Run a solution to unlock feedback and your next recommendation.</p>}</article></div>
        </main></div></div></div>;
}
